server:
    port: 8088


file:
    save:
        path: F:/upload-dir
    url:
        path: http://127.0.0.1:8081/
    upload:
        url:
            path: http://127.0.0.1:8081/uploadFile

logging:
    config: classpath:log4j2.yml
spring:
  http:
    multipart:
      max-file-size: "2MB"
  thymeleaf:
    cache: false
  ## Redis 配置
  redis:
    ## Redis服务器地址
    host: 192.168.1.234
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接端口
    port: 6381
    ## Redis服务器连接密码（默认为空）
    password: 123456
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      max-active: 500
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ## 连接池中的最大空闲连接
      max-idle: 50
      ## 连接池中的最小空闲连接
      min-idle: 10
    ## 连接超时时间（毫秒）
    timeout: 10000
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://192.168.1.221:2081
    scan: com.lezai17